# PostgreSQL receiver configuration for New Relic
receivers:
  postgresql:
    endpoint: host.docker.internal:5432
    username: newrelic_monitor  
    password: monitor123
    databases:
      - testdb
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true

processors:
  batch:
    timeout: 5s
    
  # Convert metrics to logs for the verification script
  transform:
    log_statements:
      - context: datapoint
        statements:
          - set(body, attributes)
    
  attributes:
    actions:
      - key: collector.name
        value: database-intelligence
        action: insert
      - key: instrumentation.provider
        value: opentelemetry
        action: insert
      - key: database_name
        value: testdb
        action: insert
      - key: entity.type
        value: DATABASE
        action: insert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 10
    
  otlp:
    endpoint: "https://otlp.nr-data.net:4318"
    headers:
      api-key: "fdd7bc15d64d85dc910f34aa35f0cc0eFFFFNRAL"
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000

service:
  telemetry:
    logs:
      level: info
      
  pipelines:
    metrics:
      receivers: [postgresql]
      processors: [attributes, batch]
      exporters: [debug, otlp]
      
    # Also send as logs for the verification script
    logs:
      receivers: [postgresql]
      processors: [transform, attributes, batch]
      exporters: [otlp]