# Simple collector configuration for testing database connectivity
receivers:
  # Simple PostgreSQL query
  sqlquery:
    driver: postgres
    dsn: "postgres://newrelic_monitor:monitor123@host.docker.internal:5432/testdb?sslmode=disable"
    collection_interval: 10s
    queries:
      - sql: "SELECT current_database() as db_name, count(*) as connection_count FROM pg_stat_activity GROUP BY current_database()"
        logs:
          - body_column: "db_name"

processors:
  batch:
    timeout: 5s
    
  attributes:
    actions:
      - key: collector.name
        value: database-intelligence
        action: insert
      - key: instrumentation.provider
        value: opentelemetry
        action: insert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100
    
  otlp:
    endpoint: "https://otlp.nr-data.net:4318"
    headers:
      api-key: "fdd7bc15d64d85dc910f34aa35f0cc0eFFFFNRAL"

service:
  telemetry:
    logs:
      level: debug
      
  pipelines:
    logs:
      receivers: [sqlquery]
      processors: [attributes, batch]
      exporters: [debug, otlp]