# PostgreSQL connection configuration
connection_string = "postgres://postgres:password@postgres-newrelic:5432/testdb"
databases = ["testdb"]

# Instance identification
instance_id = "postgres-prod-01"
cluster_name = "production"

# Slow query configuration with dimensional metrics
[slow_queries]
enabled = true
min_duration_ms = 100  # Lower threshold for better visibility
interval = 30
# Cardinality control
max_unique_queries = 1000
max_tables_tracked = 500
sample_rate = 1.0  # Sample all queries initially

# Query categorization rules
[slow_queries.categories]
system = ["^SELECT.*FROM\\s+pg_", "^SELECT.*FROM\\s+information_schema"]
vacuum = ["^VACUUM", "^ANALYZE"]
ddl = ["^CREATE", "^ALTER", "^DROP"]
dml = ["^INSERT", "^UPDATE", "^DELETE"]
select = ["^SELECT"]

# Blocking sessions configuration
[blocking_sessions]
enabled = true
min_blocking_duration_ms = 100
interval = 30

# Connection pool monitoring
[connections]
enabled = true
interval = 30
track_by_user = true
track_by_application = true
track_by_state = true

# Lock monitoring
[locks]
enabled = true
interval = 30
track_heavyweight_locks = true
track_lightweight_locks = false  # Too high cardinality

# Replication monitoring
[replication]
enabled = true
interval = 30

# OTLP output configuration for New Relic
[outputs.otlp]
enabled = true
endpoint = "http://otel-collector-newrelic:4317"
timeout_seconds = 30
compression = "gzip"

# Resource attributes - Entity identification
[outputs.otlp.resource_attributes]
"service.name" = "postgresql"
"service.namespace" = "production"
"service.version" = "15.3"
"db.system" = "postgresql"
"db.connection_string" = "postgresql://postgres-newrelic:5432"
"server.address" = "postgres-newrelic"
"server.port" = "5432"
"deployment.environment" = "production"

# Additional attributes for New Relic entity synthesis
[outputs.otlp.resource_attributes.custom]
"newrelic.entity.type" = "POSTGRESQL_INSTANCE"
"newrelic.entity.name" = "postgres-prod-01"
"cluster.name" = "production-cluster"

# Cardinality limits
[cardinality_limits]
max_query_fingerprints = 1000
max_table_names = 500
max_user_names = 100
max_client_applications = 50
max_schemas = 50

# Dimension allowlists
[dimensions.allowlists]
important_users = ["app_user", "analytics_user", "admin_user"]
important_applications = ["web_app", "api_service", "analytics_job"]
important_schemas = ["public", "analytics", "reporting"]

# Metric naming for New Relic
[metric_naming]
prefix = "postgresql"
use_hierarchical_names = true
include_unit_in_name = false