# Local configuration for testing
connection_string = "postgresql://postgres:postgres@localhost:5432/testdb"
host = "localhost"
port = 5432
databases = ["testdb"]
max_connections = 5
connect_timeout_secs = 30

collection_interval_secs = 30
collection_mode = "nri"
query_monitoring_count_threshold = 20
query_monitoring_response_time_threshold = 500
max_query_length = 4096

enable_extended_metrics = true
enable_ash = true
ash_sample_interval_secs = 1
ash_retention_hours = 1
ash_max_memory_mb = 100
enable_ebpf = false

sanitize_query_text = true
sanitization_mode = "smart"

[sampling]
mode = "fixed"
base_sample_rate = 1.0
rules = []

[outputs.nri]
enabled = true
entity_key = "localhost:5432"
integration_name = "com.newrelic.postgresql"

[outputs.otlp]
enabled = false
endpoint = "http://localhost:4318"
compression = "gzip"
timeout_secs = 30
headers = []