{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "database-intelligence.capabilities.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "database-intelligence.fullname" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "database-intelligence.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
{{- end }}