apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-intelligence.fullname" . }}
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.health.port }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.config.exporters.prometheus.enabled }}
    - port: {{ .Values.service.prometheus.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    {{- end }}
    {{- if .Values.config.receivers.otlp }}
    - port: {{ .Values.service.otlp.grpc.port }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.otlp.http.port }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    {{- end }}
  selector:
    {{- include "database-intelligence.selectorLabels" . | nindent 4 }}

---
{{- if .Values.service.health.annotations }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-intelligence.fullname" . }}-health
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: health
  annotations:
    {{- toYaml .Values.service.health.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.health.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "database-intelligence.selectorLabels" . | nindent 4 }}
{{- end }}

---
{{- if and .Values.config.exporters.prometheus.enabled .Values.service.prometheus.annotations }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-intelligence.fullname" . }}-prometheus
  labels:
    {{- include "database-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  annotations:
    {{- toYaml .Values.service.prometheus.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "database-intelligence.selectorLabels" . | nindent 4 }}
{{- end }}