apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config-base
  namespace: postgres-monitoring
data:
  config.toml: |
    # PostgreSQL Unified Collector Base Configuration
    # This will be overridden/patched by overlays
    
    [general]
    collection_interval_secs = 30
    collection_timeout_secs = 10
    max_connections = 10
    connect_timeout_secs = 30
    log_level = "${RUST_LOG:-info}"
    enable_extended_metrics = true
    enable_individual_queries = true
    health_port = 8080
    metrics_port = 9090
    mode = "${COLLECTOR_MODE:-hybrid}"
    
    [database]
    host = "${POSTGRES_HOST}"
    port = "${POSTGRES_PORT}"
    databases = ["${POSTGRES_DATABASE}"]
    connection_string = "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=prefer"
    
    [query_monitoring]
    count_threshold = 20
    response_time_threshold = 500.0
    
    [query_sanitization]
    sanitize_query_text = true
    sanitization_mode = "smart"
    
    [ash]
    enable_ash = true
    sample_interval_secs = 15
    retention_hours = 24
    max_memory_mb = 256
    
    # Output configurations will be patched by overlays
    [outputs.nri]
    enabled = false
    entity_key = "postgres:${POSTGRES_HOST}:${POSTGRES_PORT}"
    
    [outputs.otlp]
    enabled = false
    endpoint = "http://otel-collector:4317"
    headers = { "api-key" = "${NEW_RELIC_LICENSE_KEY}" }