apiVersion: v1
kind: Service
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
  labels:
    app: postgres-collector
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: postgres-collector
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP