apiVersion: v1
kind: Service
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
  labels:
    app: postgres-collector
spec:
  type: ClusterIP
  selector:
    app: postgres-collector
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP