apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-collector.fullname" . }}
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
data:
  config.toml: |
{{ tpl .Values.configFile . | indent 4 }}