{{- if not .Values.postgresql.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-collector.postgresqlSecretName" . }}
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
{{- if not .Values.newrelic.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-collector.newrelicSecretName" . }}
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
type: Opaque
data:
  license-key: {{ .Values.newrelic.licenseKey | b64enc | quote }}
{{- end }}
{{- if and .Values.pgbouncer.enabled (not .Values.pgbouncer.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-collector.pgbouncerSecretName" . }}
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.pgbouncer.password | b64enc | quote }}
{{- end }}