apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-collector.fullname" . }}
  labels:
    {{- include "postgres-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "postgres-collector.selectorLabels" . | nindent 4 }}