# Production Overlay - Enhanced resources and monitoring
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-monitoring

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: postgres-collector
    count: 2

patchesStrategicMerge:
  - deployment-resources.yaml
  - deployment-affinity.yaml

secretGenerator:
  - name: postgres-credentials
    type: Opaque
    behavior: replace
    envs:
      - secrets.env
  - name: newrelic-credentials
    type: Opaque  
    behavior: replace
    envs:
      - newrelic.env

images:
  - name: postgres-unified-collector
    newName: your-registry.io/postgres-unified-collector
    newTag: v1.0.0