extensions:
  health_check:
    endpoint: 0.0.0.0:13134

receivers:
  postgresql:
    endpoint: localhost:5432
    username: postgres
    password: postgres
    databases:
      - testdb
    collection_interval: 60s
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 30
  
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  resource:
    attributes:
      - key: service.name
        value: database-intelligence
        action: insert
      - key: deployment.environment  
        value: development
        action: insert

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: db_intelligence

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [postgresql]
      processors: [memory_limiter, resource, batch]
      exporters: [logging, prometheus]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888