extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  postgresql:
    endpoint: ${POSTGRES_HOST}:${POSTGRES_PORT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    databases:
      - ${POSTGRES_DATABASE}
    collection_interval: 60s
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 30
  
  batch:
    send_batch_size: 1000
    timeout: 10s
  
  resource:
    attributes:
      - key: service.name
        value: database-intelligence
        action: insert
      - key: deployment.environment  
        value: development
        action: insert

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 100
  
  otlp/newrelic:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000

service:
  pipelines:
    metrics:
      receivers: [postgresql]
      processors: [memory_limiter, resource, batch]
      exporters: [logging, otlp/newrelic]
  
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888