# Simple test configuration to verify database connectivity
receivers:
  sqlquery/test:
    driver: postgres
    dsn: "${env:PG_REPLICA_DSN}"
    collection_interval: 10s
    timeout: 5s
    queries:
      - sql: |
          SELECT 
            current_database() as database_name,
            count(*) as active_connections,
            pg_database_size(current_database()) as database_size,
            now() as collection_time
          FROM pg_stat_activity
          WHERE state = 'active'
          GROUP BY current_database()
        logs:
          - body_column: database_name
            attributes:
              - attribute_column: active_connections
              - attribute_column: database_size  
              - attribute_column: collection_time

processors:
  batch:
    timeout: 5s

  attributes:
    actions:
      - key: collector.name
        value: database-intelligence
        action: insert
      - key: instrumentation.provider
        value: opentelemetry
        action: insert

exporters:
  debug:
    verbosity: detailed
    
  otlp:
    endpoint: "${env:OTLP_ENDPOINT:-https://otlp.nr-data.net:4318}"
    headers:
      api-key: "${env:NEW_RELIC_LICENSE_KEY}"

service:
  telemetry:
    logs:
      level: debug
      
  pipelines:
    logs:
      receivers: [sqlquery/test]
      processors: [attributes, batch]
      exporters: [debug, otlp]