# Connection settings for Docker
connection_string = "postgresql://postgres:postgres@postgres:5432/testdb"
host = "postgres"
port = 5432
databases = ["testdb"]
max_connections = 5
connect_timeout_secs = 30

# Collection settings
collection_interval_secs = 30
collection_mode = "hybrid"

# OHI compatibility settings
query_monitoring_count_threshold = 20
query_monitoring_response_time_threshold = 500
max_query_length = 4095

# Extended metrics
enable_extended_metrics = true
enable_ebpf = false
enable_ash = true
ash_sample_interval_secs = 15
ash_retention_hours = 24
ash_max_memory_mb = 512

# Security settings
sanitize_query_text = true
sanitization_mode = "smart"

# Output settings
[outputs.nri]
enabled = true
entity_key = "postgres:postgres:5432"
integration_name = "com.newrelic.postgresql"

[outputs.otlp]
enabled = true
endpoint = "http://otel-collector:4318"
compression = "gzip"
timeout_secs = 10
headers = [
    ["api-key", "${NEW_RELIC_LICENSE_KEY}"]
]

# Sampling configuration
[sampling]
mode = "fixed"
base_sample_rate = 1.0
rules = []

# PgBouncer monitoring (optional)
[pgbouncer]
enabled = false
admin_connection_string = "postgresql://pgbouncer@pgbouncer:6432/pgbouncer"