[general]
collection_interval_secs = 30
collection_timeout_secs = 10
max_connections = 10
connect_timeout_secs = 30
log_level = "info"
enable_extended_metrics = true
enable_individual_queries = true
health_port = 8080
metrics_port = 9090
mode = "hybrid"

[database]
host = "localhost"
port = "5432"
databases = ["testdb"]
connection_string = "postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable"

[query_monitoring]
count_threshold = 20
response_time_threshold = 500.0

[query_sanitization]
sanitize_query_text = true
sanitization_mode = "smart"

[ash]
enable_ash = true
sample_interval_secs = 15
retention_hours = 24
max_memory_mb = 512

[outputs.nri]
enabled = true
entity_key = "postgres:localhost:5432"
integration_name = "com.newrelic.postgresql"

[outputs.otlp]
enabled = true
endpoint = "http://localhost:4317"
headers = { "api-key" = "${NEW_RELIC_LICENSE_KEY}" }