apiVersion: v1
kind: Namespace
metadata:
  name: postgres-monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres-monitoring
type: Opaque
stringData:
  username: postgres
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license
  namespace: postgres-monitoring
type: Opaque
stringData:
  key: YOUR_LICENSE_KEY_HERE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-collector-config
  namespace: postgres-monitoring
data:
  collector-config.toml: |
    connection_string = "postgresql://postgres:changeme@postgres-primary:5432/postgres"
    host = "postgres-primary"
    port = 5432
    databases = ["postgres", "myapp"]
    max_connections = 5
    connect_timeout_secs = 30
    
    collection_interval_secs = 60
    collection_mode = "hybrid"
    
    query_monitoring_count_threshold = 20
    query_monitoring_response_time_threshold = 500
    max_query_length = 4095
    
    enable_extended_metrics = true
    enable_ebpf = false
    enable_ash = true
    ash_sample_interval_secs = 1
    ash_retention_hours = 1
    
    [outputs.nri]
    enabled = true
    entity_key = "${HOSTNAME}:${PORT}"
    integration_name = "com.newrelic.postgresql"
    
    [outputs.otlp]
    enabled = true
    endpoint = "http://otel-collector:4317"
    compression = "gzip"
    timeout_secs = 30
    
    [sampling]
    mode = "adaptive"
    base_sample_rate = 1.0
    
    [[sampling.rules]]
    condition = "query_count > 1000/min"
    sample_rate = 0.1
    
    [[sampling.rules]]
    condition = "avg_elapsed_time_ms > 1000"
    sample_rate = 1.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-collector
subjects:
- kind: ServiceAccount
  name: postgres-collector
  namespace: postgres-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
  labels:
    app: postgres-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-collector
  template:
    metadata:
      labels:
        app: postgres-collector
    spec:
      serviceAccountName: postgres-collector
      containers:
      - name: collector
        image: postgres-unified-collector:latest
        imagePullPolicy: Always
        command: ["postgres-unified-collector"]
        args: ["--config", "/etc/collector/collector-config.toml"]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: key
        - name: OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        volumeMounts:
        - name: config
          mountPath: /etc/collector
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep postgres-unified-collector | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep postgres-unified-collector | grep -v grep"
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: postgres-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-collector-metrics
  namespace: postgres-monitoring
  labels:
    app: postgres-collector
spec:
  selector:
    app: postgres-collector
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP