apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-infra
  namespace: postgres-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-infra
rules:
- apiGroups: [""]
  resources:
    - nodes
    - nodes/metrics
    - nodes/stats
    - nodes/proxy
    - pods
    - services
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-infra
subjects:
- kind: ServiceAccount
  name: newrelic-infra
  namespace: postgres-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: newrelic-infra
  namespace: postgres-monitoring
  labels:
    app: newrelic-infra
spec:
  selector:
    matchLabels:
      name: newrelic-infra
  template:
    metadata:
      labels:
        name: newrelic-infra
    spec:
      serviceAccountName: newrelic-infra
      hostNetwork: true
      hostPID: true
      containers:
      - name: newrelic-infra
        image: newrelic/infrastructure:latest
        securityContext:
          privileged: true
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-license
              key: license-key
        - name: NRIA_VERBOSE
          value: "0"
        - name: NRIA_CLUSTER_NAME
          value: "postgres-monitoring"
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"environment":"k8s-test","cluster":"postgres-collector"}'
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: host-var-run
          mountPath: /var/run
        - name: host-sys
          mountPath: /sys
          readOnly: true
        - name: host-docker-socket
          mountPath: /var/run/docker.sock
        resources:
          limits:
            memory: 300M
          requests:
            cpu: 100m
            memory: 150M
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: host-var-run
        hostPath:
          path: /var/run
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-docker-socket
        hostPath:
          path: /var/run/docker.sock