# Kubernetes Secrets Template
# Copy this file to secrets.yaml and fill in your actual values
# DO NOT commit secrets.yaml to version control

apiVersion: v1
kind: Secret
metadata:
  name: newrelic-credentials
  namespace: postgres-monitoring
type: Opaque
stringData:
  license-key: "YOUR_NEW_RELIC_LICENSE_KEY_HERE"
  api-key: "YOUR_NEW_RELIC_API_KEY_HERE"
  account-id: "YOUR_NEW_RELIC_ACCOUNT_ID_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres-monitoring
type: Opaque
stringData:
  username: "postgres"
  password: "YOUR_POSTGRES_PASSWORD_HERE"
  database: "testdb"