# Database Intelligence Secrets
# IMPORTANT: Replace placeholder values with actual credentials before applying

apiVersion: v1
kind: Secret
metadata:
  name: newrelic-credentials
  namespace: monitoring
  labels:
    app: nr-db-intelligence
    component: credentials
type: Opaque
stringData:
  # New Relic License Key - REPLACE WITH ACTUAL KEY
  license-key: "NRAL-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: monitoring
  labels:
    app: nr-db-intelligence
    component: credentials
type: Opaque
stringData:
  # PostgreSQL Read Replica Connection String
  # Format: postgres://username:password@hostname:port/database?sslmode=require
  # CRITICAL: Must point to read replica, never primary database
  pg-replica-dsn: "postgres://newrelic_monitor:CHANGE_ME_PASSWORD@postgres-replica.database.svc.cluster.local:5432/production?sslmode=require&application_name=db-intelligence-collector"
  
  # MySQL Read Replica Connection String (Optional)
  # Format: username:password@tcp(hostname:port)/database?tls=true
  mysql-readonly-dsn: "newrelic_monitor:CHANGE_ME_PASSWORD@tcp(mysql-replica.database.svc.cluster.local:3306)/production?tls=true&charset=utf8mb4"

---
# TLS Certificates for Database Connections (if using custom CA)
apiVersion: v1
kind: Secret
metadata:
  name: database-tls-certs
  namespace: monitoring
  labels:
    app: nr-db-intelligence
    component: tls
type: Opaque
data:
  # Base64 encoded CA certificate
  # ca.crt: LS0tLS1CRUdJTi...
  
  # Base64 encoded client certificate (if using mutual TLS)
  # client.crt: LS0tLS1CRUdJTi...
  
  # Base64 encoded client key (if using mutual TLS)
  # client.key: LS0tLS1CRUdJTi...

---
# Optional: Registry credentials for custom collector image
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: monitoring
  labels:
    app: nr-db-intelligence
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker config JSON
  # .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5jb20iOiB7CiAgICAgICJhdXRoIjogImJHOW5hVzQ2Y0dGemMzZHZjbVE9IgogICAgfQogIH0KfQ==