# OpenTelemetry Collector Builder Configuration
# OTEL-First approach: Maximize standard components, minimize custom code

dist:
  name: database-intelligence
  description: "OTEL-First Database Intelligence Collector"
  output_path: ./dist
  otelcol_version: "0.128.0"

extensions:
  # Standard extensions only
  - gomod: go.opentelemetry.io/collector/extension/healthcheckextension v0.128.0
  - gomod: go.opentelemetry.io/collector/extension/pprofextension v0.128.0
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.128.0

receivers:
  # Standard OTEL receivers - no custom receivers needed!
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.128.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.128.0

processors:
  # Standard OTEL processors
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.128.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.128.0
  
  # Custom processors only for OTEL gaps (optional)
  - gomod: github.com/database-intelligence/database-intelligence-mvp/processors/adaptivesampler v0.1.0
    path: ./processors/adaptivesampler
  - gomod: github.com/database-intelligence/database-intelligence-mvp/processors/circuitbreaker v0.1.0
    path: ./processors/circuitbreaker

exporters:
  # Standard OTEL exporters only
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.128.0

providers:
  # Standard providers
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v0.128.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v0.128.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.128.0