# OpenTelemetry Collector Builder Configuration
# This builds a custom collector with our components

dist:
  name: database-intelligence-collector
  description: "Database Intelligence OpenTelemetry Collector Distribution"
  output_path: ./dist
  otelcol_version: "0.127.0"

extensions:
  # Simplified extension set for build test
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.127.0

receivers:
  # Standard receivers
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.127.0
  
  # Note: Custom postgresqlquery receiver removed - use standard receivers instead
  # - postgresql receiver for database metrics  
  # - sqlquery receiver for query performance data

processors:
  # Standard processors
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.127.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.127.0
  
  # Custom processors - planattributeextractor only for now
  # - gomod: github.com/database-intelligence-mvp/processors/adaptivesampler v0.1.0
  #   path: ./processors/adaptivesampler
  # - gomod: github.com/database-intelligence-mvp/processors/circuitbreaker v0.1.0
  #   path: ./processors/circuitbreaker
  - gomod: github.com/database-intelligence-mvp/processors/planattributeextractor v0.1.0
    path: ./processors/planattributeextractor
  # - gomod: github.com/database-intelligence-mvp/processors/verification v0.1.0
  #   path: ./processors/verification

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.127.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.127.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.127.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.127.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v0.127.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v0.127.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v0.127.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.127.0