# OpenTelemetry Collector Builder Configuration
# Simplified OTEL-First approach

dist:
  name: database-intelligence
  description: Database Intelligence Collector - OTEL-First Implementation
  output_path: ./bin
  version: 1.0.0
  otelcol_version: 0.96.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.96.0

receivers:
  # Database receivers
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.96.0

processors:
  # Standard processors
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.96.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.96.0
  
  # Custom processors for gaps
  - gomod: github.com/database-intelligence-mvp/processors/adaptivesampler v1.0.0
    path: ./processors/adaptivesampler
  - gomod: github.com/database-intelligence-mvp/processors/circuitbreaker v1.0.0
    path: ./processors/circuitbreaker

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.96.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.96.0