# PostgreSQL Unified Collector Configuration
# This config file uses environment variables

# Connection settings
connection_string = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
host = "${POSTGRES_HOST}"
port = "${POSTGRES_PORT}"
databases = ["${POSTGRES_DATABASE}"]
max_connections = 5
connect_timeout_secs = 30

# Collection settings
collection_interval_secs = "${COLLECTION_INTERVAL_SECS}"
collection_mode = "${COLLECTOR_MODE}"

# OHI compatibility settings
query_monitoring_count_threshold = "${QUERY_MONITORING_COUNT_THRESHOLD}"
query_monitoring_response_time_threshold = "${QUERY_MONITORING_RESPONSE_TIME_THRESHOLD}"
max_query_length = 4096

# Extended metrics
enable_extended_metrics = "${ENABLE_EXTENDED_METRICS}"
enable_ebpf = "${ENABLE_EBPF}"
enable_ash = "${ENABLE_ASH}"
ash_sample_interval_secs = 1
ash_retention_hours = 1

# Security settings
sanitize_query_text = "${SANITIZE_QUERY_TEXT}"
sanitization_mode = "${SANITIZATION_MODE}"

# Output configuration
[outputs.nri]
enabled = true
entity_key = "${NRI_ENTITY_KEY}"
integration_name = "${NRI_INTEGRATION_NAME}"

[outputs.otlp]
enabled = true
endpoint = "${OTLP_ENDPOINT}"
compression = "${OTLP_COMPRESSION}"
timeout_secs = 30
headers = []

# Sampling configuration
[sampling]
mode = "fixed"
base_sample_rate = 1.0

[[sampling.rules]]
condition = "query_duration > 500"
sample_rate = 1.0