# PostgreSQL Unified Collector Configuration

# Connection settings
connection_string = "postgresql://postgres:password@localhost:5432/postgres"
host = "localhost"
port = 5432
databases = ["postgres"]
max_connections = 5
connect_timeout_secs = 30

# Collection settings
collection_interval_secs = 60
collection_mode = "hybrid"  # "otel", "nri", or "hybrid"

# OHI compatibility settings
query_monitoring_count_threshold = 20
query_monitoring_response_time_threshold = 500
max_query_length = 4095

# Extended metrics
enable_extended_metrics = true
enable_ebpf = false
enable_ash = true
ash_sample_interval_secs = 1
ash_retention_hours = 1

# Output configuration
[outputs.nri]
enabled = true
entity_key = "${HOSTNAME}:${PORT}"
integration_name = "com.newrelic.postgresql"

[outputs.otlp]
enabled = true
endpoint = "http://localhost:4317"
compression = "gzip"
timeout_secs = 30

# Headers for authentication (optional)
# headers = [
#     ["api-key", "${NEW_RELIC_API_KEY}"],
# ]

# Adaptive sampling configuration
[sampling]
mode = "adaptive"  # "fixed" or "adaptive"
base_sample_rate = 1.0

[[sampling.rules]]
condition = "query_count > 1000/min"
sample_rate = 0.1

[[sampling.rules]]
condition = "avg_elapsed_time_ms > 1000"
sample_rate = 1.0

[[sampling.rules]]
condition = "statement_type = 'DDL'"
sample_rate = 1.0