# New Relic Infrastructure Agent Configuration
license_key: ${NRIA_LICENSE_KEY}

# Agent behavior
enable_process_metrics: true
payload_compression_level: 6

# Custom attributes
custom_attributes:
  environment: test
  service: postgresql
  collector: unified

# Logging
log:
  level: info
  file: /var/log/newrelic-infra/newrelic-infra.log
  forward: true
  stdout: true

# Integration configuration
integrations_config_refresh: 60s

# Features
features:
  docker_enabled: true