integrations:
  - name: nri-postgresql
    env:
      HOSTNAME: localhost
      PORT: 5432
      USERNAME: postgres
      PASSWORD: password
      DATABASE: postgres
      COLLECTION_LIST: '{"postgres": {"schemas": ["public", "pg_catalog"]}}'
      ENABLE_SSL: false
      QUERY_MONITORING_COUNT_THRESHOLD: 20
      QUERY_MONITORING_RESPONSE_TIME_THRESHOLD: 500
      ENABLE_EXTENDED_METRICS: true
      ENABLE_ASH: true
      ENABLE_EBPF: false
    interval: 60s
    timeout: 30s