# OpenTelemetry PostgreSQL Collector Configuration

# Connection settings
connection_string = "postgresql://postgres:password@localhost:5432/postgres"
host = "localhost"
port = 5432
databases = ["postgres"]
max_connections = 5
connect_timeout_secs = 30

# Collection settings
collection_interval_secs = 60
collection_mode = "otel"

# Query monitoring
query_monitoring_count_threshold = 20
query_monitoring_response_time_threshold = 500
max_query_length = 4096

# Extended metrics
enable_extended_metrics = true
enable_ebpf = false
enable_ash = true
ash_sample_interval_secs = 1
ash_retention_hours = 24

# Output configuration
[outputs.otlp]
enabled = true
endpoint = "http://localhost:4317"
compression = "gzip"
timeout_secs = 30
headers = [
    ["x-otel-service-name", "postgresql"],
]

# Sampling configuration
[sampling]
mode = "adaptive"
base_sample_rate = 0.1

[[sampling.rules]]
condition = "query_duration > 500"
sample_rate = 1.0