# RBAC Configuration for PostgreSQL Unified Collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-collector
  namespace: postgres-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-collector
rules:
  # Core API access
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  # Apps API access
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  # Metrics API access
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-collector
subjects:
  - kind: ServiceAccount
    name: postgres-collector
    namespace: postgres-monitoring

---
# Role for namespace-specific permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-collector
subjects:
  - kind: ServiceAccount
    name: postgres-collector
    namespace: postgres-monitoring