apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-collector
  namespace: postgres-monitoring
  labels:
    app: postgres-collector
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: postgres-collector
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'go_.*'
          action: drop