global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          instance: 'otel-collector'
  
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          instance: 'postgres-demo'