apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-collector
spec:
  template:
    spec:
      containers:
      - name: collector
        env:
        - name: COLLECTOR_MODE
          value: "nri"