version: '3'

tasks:
  binary:
    desc: Build collector binary for current platform
    vars:
      OUTPUT: '{{.OUTPUT | default (print .DIST_DIR "/" .BINARY_NAME)}}'
      GOOS: '{{.GOOS | default OS}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
    cmds:
      - echo "🔨 Building for {{.GOOS}}/{{.GOARCH}}..."
      - mkdir -p {{.DIST_DIR}}
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} \
        ocb --config=ocb-config.yaml \
            --output-path={{.OUTPUT}}-{{.GOOS}}-{{.GOARCH}}
      - |
        if [ "{{.GOOS}}/{{.GOARCH}}" = "{{OS}}/{{ARCH}}" ]; then
          cp {{.OUTPUT}}-{{.GOOS}}-{{.GOARCH}} {{.OUTPUT}}
        fi
      - echo "✅ Built: {{.OUTPUT}}-{{.GOOS}}-{{.GOARCH}}"

  multi:
    desc: Build for multiple platforms
    cmds:
      - task: build:binary
        vars:
          GOOS: linux
          GOARCH: amd64
      - task: build:binary
        vars:
          GOOS: linux
          GOARCH: arm64
      - task: build:binary
        vars:
          GOOS: darwin
          GOARCH: amd64
      - task: build:binary
        vars:
          GOOS: darwin
          GOARCH: arm64
      - echo "✅ Multi-platform build complete"

  docker:
    desc: Build Docker image
    vars:
      IMAGE: '{{.DOCKER_REGISTRY}}/{{.DOCKER_ORG}}/{{.BINARY_NAME}}'
      TAG: '{{.TAG | default .VERSION}}'
      PLATFORM: '{{.PLATFORM | default "linux/amd64,linux/arm64"}}'
    deps: [binary]
    cmds:
      - echo "🐳 Building Docker image: {{.IMAGE}}:{{.TAG}}"
      - |
        docker buildx build \
          --platform {{.PLATFORM}} \
          --tag {{.IMAGE}}:{{.TAG}} \
          --tag {{.IMAGE}}:latest \
          {{if .PUSH}}--push{{else}}.{{end}}

  docker:push:
    desc: Build and push Docker image
    cmds:
      - task: build:docker
        vars:
          PUSH: true

  processors:
    desc: Build only custom processors
    cmds:
      - echo "🔨 Building custom processors..."
      - go build -v ./processors/adaptivesampler/...
      - go build -v ./processors/circuitbreaker/...
      - go build -v ./processors/planattributeextractor/...
      - go build -v ./processors/verification/...
      - echo "✅ Processors built"

  quick:
    desc: Quick build without OCB (for development)
    cmds:
      - echo "🚀 Quick build..."
      - go build -o {{.DIST_DIR}}/{{.BINARY_NAME}}-dev ./main.go
      - echo "✅ Development build ready"

  release:
    desc: Build release artifacts
    vars:
      VERSION: '{{.VERSION}}'
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "❌ VERSION is required"
          exit 1
        fi
      - task: build:multi
      - task: build:docker
        vars:
          TAG: '{{.VERSION}}'
      - task: helm:package
      - |
        echo "📦 Creating release archive..."
        cd {{.DIST_DIR}} && \
        tar czf {{.BINARY_NAME}}-{{.VERSION}}.tar.gz \
          {{.BINARY_NAME}}-* \
          *.tgz
      - echo "✅ Release {{.VERSION}} ready in {{.DIST_DIR}}/"